apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-app
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
{{- range .Values.queries }}
            - name: {{ .name | upper | replace "-" "_" }}_QUERY
              value: {{ .query | quote }}
            - name: {{ .name | upper | replace "-" "_" }}_DATABASE
              value: {{ .databaseName | quote }}
{{- end }}
{{ if eq .Values.databaseCredentials.source.kind "secret" }}
          envFrom:
          - secretRef:
              name: {{ .Values.databaseCredentials.source.name }}
{{ else if eq .Values.databaseCredentials.source.kind "cm" }}
          envFrom:
          - configMapRef:
              name: {{ .Values.databaseCredentials.source.name }}
{{ end }}