image:
  name: wiktorkisielewski/prometheus-psql-exporter
  tag: 0.0.3

# each query should return a single value
queries:
  - name: example-query
    query: "SELECT COUNT(*) FROM SOME_TABLE;"
    databaseName: some_database
  - name: example-query-2
    query: "SELECT COUNT(*) FROM OTHER_TABLE;"
    databaseName: other_database

databaseCredentials:
  # source.kind can be set to "cm" [configMap] or "secret"
  source: 
    kind: cm
    name: cm_name