name: docker image - build & push

on:
  push:
    tags:
    - '*'

jobs:
  release_psql-exporter:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    env:
      DOCKER_BUILD_CONTEXT_PATH: "./exporter"
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Create docker image tag
        run: echo "DOCKER_IMAGE_TAG=$(echo ${{ github.ref }} | sed 's|refs/tags/||g')" >> $GITHUB_ENV
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER_BUILD_CONTEXT_PATH }}
          tags: |
            wiktorkisielewski/prometheus-psql-exporter:${{ env.DOCKER_IMAGE_TAG }}
          push: true
